# 1.0 BUSINESS UNDERSTANDING

## 1.1 Business Overview
Modern streaming platforms host thousands of movies, often leaving users overwhelmed by endless choices trapping users into endless scrolling cycles.
Recommendation systems can solve this problem by personalizing the discovery process. Instead of forcing users to search through thousands of movies, the system automatically finds matches for them. By analyzing movie details like plot summaries and genres the system calculates how similar movies are to each other. This stops users from feeling overwhelmed by too many choices and helps them find something to watch instantly.

In this project, a content-based movie recommendation system will be built that makes discovering of new movie faster, easier, and matched to what the user wants to watch.

## 1.2 Problem Statement
With thousands of titles available on modern streaming platforms, users are often overwhelmed by choice, trapping them in endless scrolling cycles. Manually searching through massive catalogs is tedious and frustrating, which ultimately reduces user satisfaction and engagement.
This project addresses this issue by developing a content-based movie recommendation system. By leveraging textual similarity techniques to analyze key movie features, the system automatically identifies and suggests closely related titles turning endless searching into instant, tailored discovery.

## 1.3 Project Objectives

- To preprocess and transform textual movie data into meaningful representation for analysis
- To transform movie information into meaningful numerical representations
- To apply Natural Language Processing (NLP) techniques such as tokenization, stemming, vectorization
- To measure similarity between movies using cosine similarity and generate accurate movie recommendations 
- To build a content-based movie recommendation system and improve movie discovery and user experience through personalized recommendations

## 1.4 Research Questions

- How can textual metadata be used to recommend similar movies and TV shows?
- Which NLP techniques are most effective for content-based recommendation?
- How well does TF-IDF vectorization capture content similarity?
- Can cosine similarity effectively identify related movie content?

## 1.5 Success Criteria

The project will be considered successful if:

- Similar movies are grouped effectively
- Recommendations are generated efficiently
- The recommendation results improve content discovery

# 2.0 DATA UNDERSTANDING

## 2.1 Data Source

TMDB movie data is used as the primary data:
- movies.csv
- credits.csv

These datasets contain movie metadata such as:
- Movie titles
- Genres
- Keywords
- Cast information
- Crew information
- Movie overviews (descriptions)
- Popularity and rating metrics

## 2.2 Load Datasets

In [1]:
import pandas as pd
movies = pd.read_csv("./data/tmdb_5000_movies.csv")
# Displays the first five rows of the movies dataset.
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,vote_average,vote_count
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2009-12-10,2787965087,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2007-05-19,961000000,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...","[{""iso_3166_1"": ""GB"", ""name"": ""United Kingdom""...",2015-10-26,880674609,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-07-16,1084939099,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]","[{""iso_3166_1"": ""US"", ""name"": ""United States o...",2012-03-07,284139100,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124

In [2]:
credits = pd.read_csv("./data/tmdb_5000_credits.csv")
# Displays the first five rows of the credits dataset.
credits.head()

,movie_id,title,cast,crew
0,19995,Avatar,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [3]:
# check for present columns
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count'],
      dtype='object')

In [4]:
# check for present columns
credits.columns

Index(['movie_id', 'title', 'cast', 'crew'], dtype='object')

In [5]:
# Displays column names, data types, and missing values in the movies dataset.
movies.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 20 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   budget                4803 non-null   int64
 1   genres                4803 non-null   object
 2   homepage              1712 non-null   object
 3   id                    4803 non-null   int64
 4   keywords              4803 non-null   object
 5   original_language     4803 non-null   object
 6   original_title        4803 non-null   object
 7   overview              4800 non-null   object
 8   popularity            4803 non-null   float64
 9   production_companies  4803 non-null   object
 10  production_countries  4803 non-null   object
 11  release_date          4802 non-null   object
 12  revenue               4803 non-null   int64
 13  runtime               4801 non-null   float64
 14  spoken_languages      4803 non-null   object
 15  status                4803 non-null   object
 16  tagline               3959 non-null   object
 17  title                 4803 non-null   object
 18  vote_average          4803 non-null   float64
 19  vote_count            4803 non-null   int64
dtypes: float64(3), int64(4), object(13)
memory usage: 750.6+ KB

In [6]:
# Displays the structure of the credits dataset.
credits.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4803 entries, 0 to 4802
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   movie_id  4803 non-null   int64
 1   title     4803 non-null   object
 2   cast      4803 non-null   object
 3   crew      4803 non-null   object
dtypes: int64(1), object(3)
memory usage: 150.2+ KB

In [7]:
# check for missing values in movies dataset
movies.isnull().sum().sort_values(ascending=False)

homepage                3091
tagline                  844
overview                   3
runtime                    2
release_date               1
budget                     0
vote_average               0
title                      0
status                     0
spoken_languages           0
revenue                    0
production_countries       0
genres                     0
production_companies       0
popularity                 0
original_title             0
original_language          0
keywords                   0
id                         0
vote_count                 0
dtype: int64

In [8]:
# Check for missing values in the credits dataset.
credits.isnull().sum()

movie_id    0
title       0
cast        0
crew        0
dtype: int64

In [9]:
# Check for duplicates
movies.duplicated().sum()
credits.duplicated().sum()

0

In [10]:
# statistical summary for numerical columns.
movies.describe()

,budget,id,popularity,revenue,runtime,vote_average,vote_count
count,4.803000e+03,4803.000000,4803.000000,4.803000e+03,4801.000000,4803.000000,4803.000000
mean,2.904504e+07,57165.484281,21.492301,8.226064e+07,106.875859,6.092172,690.217989
std,4.072239e+07,88694.614033,31.816650,1.628571e+08,22.611935,1.194612,1234.585891
min,0.000000e+00,5.000000,0.000000,0.000000e+00,0.000000,0.000000,0.000000
25%,7.900000e+05,9014.500000,4.668070,0.000000e+00,94.000000,5.600000,54.000000
50%,1.500000e+07,14629.000000,12.921594,1.917000e+07,103.000000,6.200000,235.000000
75%,4.000000e+07,58610.500000,28.313505,9.291719e+07,118.000000,6.800000,737.000000
max,3.800000e+08,459488.000000,875.581305,2.787965e+09,338.000000,10.000000,13752.000000

- The movies dataset contains 20 columns, while the credits dataset contains 4 features.
- Most columns contain complete data with very few missing values. The homepage column contains many missing values and may not be useful for recommendation modeling.
- Columns such as overview, genres, keywords, cast, and crew appear highly relevant for generating movie similarities.
- The datasets contain both numerical and textual data types.
- No duplicated rows detected

# 3.0 DATA PREPARATION

In this phase, the datasets will be cleaned and transformed into a format suitable for building the recommendation system.

The main tasks include:
- merging datasets
- selecting relevant features/columns
- handling missing values
- preprocessing textual data
- creating tags for similarity analysis

cleaning data
handling missing values
removing duplicates
feature engineering
text preprocessing
merging datasets

## 3.1 Dataset Merging

In [11]:
# Merge the movies & credits Datasets

credits.drop('title', axis=1, inplace=True)

movies = movies.merge(credits, left_on='id', right_on='movie_id')
movies.head()

,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,production_companies,...,runtime,spoken_languages,status,tagline,title,vote_average,vote_count,movie_id,cast,crew
0,237000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.avatarmovie.com/,19995,"[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...",en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,"[{""name"": ""Ingenious Film Partners"", ""id"": 289...",...,162.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}, {""iso...",Released,Enter the World of Pandora.,Avatar,7.2,11800,19995,"[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,300000000,"[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...",http://disney.go.com/disneypictures/pirates/,285,"[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...",en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}, {""...",...,169.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"At the end of the world, the adventure begins.",Pirates of the Caribbean: At World's End,6.9,4500,285,"[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,245000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://www.sonypictures.com/movies/spectre/,206647,"[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...",en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,"[{""name"": ""Columbia Pictures"", ""id"": 5}, {""nam...",...,148.0,"[{""iso_639_1"": ""fr"", ""name"": ""Fran\u00e7ais""},...",Released,A Plan No One Escapes,Spectre,6.3,4466,206647,"[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,250000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...",http://www.thedarkknightrises.com/,49026,"[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...",en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.312950,"[{""name"": ""Legendary Pictures"", ""id"": 923}, {""...",...,165.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,The Legend Ends,The Dark Knight Rises,7.6,9106,49026,"[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,260000000,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...",http://movies.disney.com/john-carter,49529,"[{""id"": 818, ""name"": ""based on novel""}, {""id"":...",en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,"[{""name"": ""Walt Disney Pictures"", ""id"": 2}]",...,132.0,"[{""iso_639_1"": ""en"", ""name"": ""English""}]",Released,"Lost in our world, found in another.",John Carter,6.1,2124,49529,"[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

In [12]:
movies.columns

Index(['budget', 'genres', 'homepage', 'id', 'keywords', 'original_language',
       'original_title', 'overview', 'popularity', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'vote_average',
       'vote_count', 'movie_id', 'cast', 'crew'],
      dtype='object')

## 3.2 Feature Selection

In [13]:
# selected only relevant columns
movies = movies[['movie_id',
                 'title',
                 'overview',
                 'genres',
                 'keywords',
                 'cast',
                 'crew']]

In [14]:
movies.head()

,movie_id,title,overview,genres,keywords,cast,crew
0,19995,Avatar,"In the 22nd century, a paraplegic Marine is di...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 1463, ""name"": ""culture clash""}, {""id"":...","[{""cast_id"": 242, ""character"": ""Jake Sully"", ""...","[{""credit_id"": ""52fe48009251416c750aca23"", ""de..."
1,285,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...","[{""id"": 12, ""name"": ""Adventure""}, {""id"": 14, ""...","[{""id"": 270, ""name"": ""ocean""}, {""id"": 726, ""na...","[{""cast_id"": 4, ""character"": ""Captain Jack Spa...","[{""credit_id"": ""52fe4232c3a36847f800b579"", ""de..."
2,206647,Spectre,A cryptic message from Bond’s past sends him o...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 470, ""name"": ""spy""}, {""id"": 818, ""name...","[{""cast_id"": 1, ""character"": ""James Bond"", ""cr...","[{""credit_id"": ""54805967c3a36829b5002c41"", ""de..."
3,49026,The Dark Knight Rises,Following the death of District Attorney Harve...,"[{""id"": 28, ""name"": ""Action""}, {""id"": 80, ""nam...","[{""id"": 849, ""name"": ""dc comics""}, {""id"": 853,...","[{""cast_id"": 2, ""character"": ""Bruce Wayne / Ba...","[{""credit_id"": ""52fe4781c3a36847f81398c3"", ""de..."
4,49529,John Carter,"John Carter is a war-weary, former military ca...","[{""id"": 28, ""name"": ""Action""}, {""id"": 12, ""nam...","[{""id"": 818, ""name"": ""based on novel""}, {""id"":...","[{""cast_id"": 5, ""character"": ""John Carter"", ""c...","[{""credit_id"": ""52fe479ac3a36847f813eaa3"", ""de..."

## 3.3 Handle Missing Values

In [15]:
# drop missing values
movies.dropna(inplace=True)

In [16]:
# check if missing values were removed
movies.isnull().sum()

movie_id    0
title       0
overview    0
genres      0
keywords    0
cast        0
crew        0
dtype: int64

In [17]:
# No duplicated rows
movies.duplicated().sum()

0

## 3.4 Feature Engineering & Natural Language Processing

Main steps include:
- converting JSON-like columns into usable lists
- extracting important features (genres, keywords, cast, crew)
- creating a unified "tags" column
- applying text preprocessing (lowercasing, tokenization, stemming)

## 3.4.1 Convert JSON-like columns into usable format & feature extraction

In [18]:
import ast
import warnings
warnings.filterwarnings('ignore')

In [19]:
# Convert stringified JSON in genres & keywords into Python objects.
def convert(obj):
    L = []
    for i in ast.literal_eval(obj):
        L.append(i['name'])
    return L

# Apply the function on the genres column
movies['genres'] = movies['genres'].apply(convert)

# Apply the function on the keywords column
movies['keywords'] = movies['keywords'].apply(convert)

In [20]:
# Clean "cast" column
def convert_cast(obj):
    L = []
    counter = 0
    for i in ast.literal_eval(obj):
        if counter != 3:
            L.append(i['name'])
            counter += 1
        else:
            break
    return L

# Apply the fuction on cast
movies['cast'] = movies['cast'].apply(convert_cast)

In [21]:
# clean "crew" column
def fetch_director(obj):
    L = []
    for i in ast.literal_eval(obj):
        if i['job'] == 'Director':
            L.append(i['name'])
            break
    return L

# Apply the function on crew
movies['crew'] = movies['crew'].apply(fetch_director)

## 3.4.2 Tokenization
* To split longsentences into individual words

In [22]:
# Converts overview text into tokens
movies['overview'] = movies['overview'].apply(lambda x: x.split())

## 3.4.3 Removal of extra spaces

In [23]:
# Remove extra spaces for consistency in text processing
def remove_spaces(L):
    return [i.replace(" ", "") for i in L]

# Apply to the columns
movies['genres'] = movies['genres'].apply(remove_spaces)
movies['keywords'] = movies['keywords'].apply(remove_spaces)
movies['cast'] = movies['cast'].apply(remove_spaces)
movies['crew'] = movies['crew'].apply(remove_spaces)

## 3.4.4 Create unified “Tags” column

* The tags column combine all important text-based features into a single column called "tags".

In [24]:
# Combine all the columns into one list per movie
movies['tags'] = movies['overview'] + movies['genres'] + movies['keywords'] + movies['cast'] + movies['crew']

# Create Final DataFrame to only essential columns for recommendation.
new_df = movies[['movie_id', 'title', 'tags']]

# Convert list of words into a single string so it can be processed by NLP models
new_df['tags'] = new_df['tags'].apply(lambda x: " ".join(x))

## 3.4.5 Lowercasing

In [25]:
# Normalize text into lowercase to ensure consistency in vectorization.
new_df['tags'] = new_df['tags'].apply(lambda x: x.lower())

## 3.4.6 Stemming

* To reduce words to their root form.

In [26]:
from nltk.stem.porter import PorterStemmer

ps = PorterStemmer()

# stem function
def stem(text):
    y = []
    for i in text.split():
        y.append(ps.stem(i))
    return " ".join(y)

# Apply stemming
new_df['tags'] = new_df['tags'].apply(stem)

# 4.0 MODELING

## 4.1 CountVectorizer as the baseline recommender

In [27]:
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.metrics.pairwise import cosine_similarity

# Initialize CountVectorizer
cv = CountVectorizer(max_features=5000, stop_words='english')

# Convert text to vectors
vectors = cv.fit_transform(new_df['tags']).toarray()

# Compute similarity matrix
similarity = cosine_similarity(vectors)

## 4.2 TF-IDF as improved Model

In [28]:
from sklearn.feature_extraction.text import TfidfVectorizer

# Initialize TF-IDF Vectorizer
tfidf = TfidfVectorizer(max_features=5000, stop_words='english')

# Convert text to vectors
vectors_tfidf = tfidf.fit_transform(new_df['tags']).toarray()

# Compute similarity matrix
similarity_tfidf = cosine_similarity(vectors_tfidf)

* Vectorization is applied to transform texts into numerical vectors for machine learning processing.
* The model limits the unique words to the 5,000 most frequent words while removing stop words (common words that do not add meaningful information).
* Cosine similarity is used to measure similarity between movies, enabling the recommendation of movies with related content.

## 4.3 Recommendation Function

In [29]:
def recommend(movie, similarity_matrix):
    movie_index = new_df[new_df['title'] == movie].index[0]
    
    distances = similarity_matrix[movie_index]
    
    movie_list = sorted(
        list(enumerate(distances)),
        reverse=True,
        key=lambda x: x[1]
    )[1:10]
    
    for i in movie_list:
        print(new_df.iloc[i[0]].title)

In [30]:
# Test Recommendations
recommend('Meet Dave', similarity_tfidf)

Escape from Planet Earth
Alien
Space Pirate Captain Harlock
Home
Planet 51
The Hitchhiker's Guide to the Galaxy
Aliens in the Attic
Journey to Saturn
Aliens vs Predator: Requiem

In [31]:
# Saving Model Files for deployment
import pickle

pickle.dump(new_df, open('movies.pkl', 'wb'))
pickle.dump(similarity_tfidf, open('similarity.pkl', 'wb'))

# 5.0 Conclusion

* A content-based movie recommendation system was successfully built using NLP techniques.
* The system processes movie metadata, transforms it into numerical vectors and computes similarity using cosine similarity to generate recommendations.